name: aml-elliptic-gpu
channels:
  - conda-forge
  - rapidsai
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - anyio=4.12.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - async-timeout=5.0.1
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.2
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=7.0.0
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorcet=3.1.0
  - contourpy=1.3.2
  - cpython=3.10.19
  - cucim=26.02.00
  - cuda-bindings=13.1.1
  - cuda-cccl_linux-64=13.1.115
  - cuda-core=0.3.2
  - cuda-crt-dev_linux-64=13.1.115
  - cuda-crt-tools=13.1.115
  - cuda-cudart=13.1.80
  - cuda-cudart-dev=13.1.80
  - cuda-cudart-dev_linux-64=13.1.80
  - cuda-cudart-static=13.1.80
  - cuda-cudart-static_linux-64=13.1.80
  - cuda-cudart_linux-64=13.1.80
  - cuda-nvcc-dev_linux-64=13.1.115
  - cuda-nvcc-impl=13.1.115
  - cuda-nvcc-tools=13.1.115
  - cuda-nvrtc=13.1.115
  - cuda-nvvm-dev_linux-64=13.1.115
  - cuda-nvvm-impl=13.1.115
  - cuda-nvvm-tools=13.1.115
  - cuda-pathfinder=1.3.3
  - cuda-profiler-api=13.1.115
  - cuda-python=13.1.1
  - cuda-version=13.1
  - cudf=26.02.01
  - cudf-polars=26.02.01
  - cudf_kafka=26.02.01
  - cugraph=26.02.00
  - cuml=26.02.00
  - cupy=13.6.0
  - cupy-core=13.6.0
  - custreamz=26.02.01
  - cuvs=26.02.00
  - cuxfilter=26.02.00
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2026.1.1
  - dask-core=2026.1.1
  - dask-cuda=26.02.00
  - dask-cudf=26.02.01
  - datashader=0.18.2
  - defusedxml=0.7.1
  - distributed=2026.1.1
  - distributed-ucxx=0.48.00
  - dlpack=0.8
  - exceptiongroup=1.3.1
  - fastrlock=0.8.3
  - folium=0.20.0
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozenlist=1.7.0
  - fsspec=2026.2.0
  - geopandas=1.1.2
  - geopandas-base=1.1.2
  - geos=3.14.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - h2=4.3.0
  - holoviews=1.22.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - isoduration=20.11.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - json-c=0.18
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-server-proxy=4.4.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab_pygments=0.3.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarchive=3.8.5
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcublas=13.2.1.1
  - libcublas-dev=13.2.1.1
  - libcucim=26.02.00
  - libcudf=26.02.01
  - libcudf_kafka=26.02.01
  - libcufft=12.1.0.78
  - libcufile=1.16.1.26
  - libcufile-dev=1.16.1.26
  - libcugraph=26.02.00
  - libcugraph_etl=26.02.00
  - libcuml=26.02.00
  - libcurand=10.4.1.81
  - libcurand-dev=10.4.1.81
  - libcurl=8.18.0
  - libcusolver=12.0.9.81
  - libcusolver-dev=12.0.9.81
  - libcusparse=12.7.3.1
  - libcusparse-dev=12.7.3.1
  - libcuvs=26.02.00
  - libcuvs-headers=26.02.00
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.11.4
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - libkvikio=26.02.00
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvcomp=5.1.0.21
  - libnvcomp-dev=5.1.0.21
  - libnvimgcodec=0.7.0
  - libnvimgcodec0=0.7.0
  - libnvjitlink=13.1.115
  - libnvjpeg=13.0.3.75
  - libnvjpeg2k0=0.9.1.47
  - libnvptxcompiler-dev=13.1.115
  - libnvptxcompiler-dev_linux-64=13.1.115
  - libnvtiff=0.6.0.78
  - libnvtiff0=0.6.0.78
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libraft=26.02.00
  - libraft-headers=26.02.00
  - libraft-headers-only=26.02.00
  - librdkafka=2.8.0
  - libre2-11=2025.11.05
  - librmm=26.02.00
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libucxx=0.48.00
  - libudev1=258.3
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.1.3
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.4.5
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markdown=3.10.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - minizip=4.0.10
  - mistune=3.2.0
  - msgpack-python=1.1.2
  - multidict=6.7.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - muparser=2.3.5
  - narwhals=2.16.0
  - nbclient=0.10.4
  - nbconvert-core=7.17.0
  - nbformat=5.10.4
  - nccl=2.29.2.1
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nodejs=25.2.1
  - numba=0.61.2
  - numba-cuda=0.22.2
  - numpy=1.26.4
  - nvidia-ml-py=13.590.48
  - nvtx=0.2.14
  - nx-cugraph=26.02.00
  - openjpeg=2.5.4
  - openssl=3.6.1
  - orc=2.2.2
  - overrides=7.7.0
  - packaging=26.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - panel=1.8.7
  - param=2.3.2
  - partd=1.4.2
  - pcre2=10.46
  - pillow=12.1.0
  - pip=26.0.1
  - platformdirs=4.5.1
  - polars=1.35.2
  - polars-runtime-32=1.35.2
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.24.1
  - propcache=0.3.1
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py-xgboost=3.1.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pyct=0.6.0
  - pygments=2.19.2
  - pylibcudf=26.02.01
  - pylibcugraph=26.02.00
  - pylibraft=26.02.00
  - pyogrio=0.11.1
  - pyparsing=3.3.2
  - pyproj=3.7.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-confluent-kafka=2.8.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.10.19
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.8.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - raft-dask=26.02.00
  - rapids=26.02.01
  - rapids-dask-dependency=26.02.00
  - rapids-logger=0.2.3
  - rapids-xgboost=26.02.01
  - rdma-core=61.0
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.3.2
  - rmm=26.02.00
  - rpds-py=0.30.0
  - s2n=1.6.2
  - scikit-image=0.20.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - send2trash=2.1.0
  - setuptools=81.0.0
  - shapely=2.1.2
  - simpervisor=1.0.0
  - six=1.17.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - soupsieve=2.8.3
  - sqlite=3.51.2
  - streamz=0.6.5
  - tblib=3.2.2
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2020.6.3
  - tinycss2=1.5.1
  - tk=8.6.13
  - toolz=1.1.0
  - tornado=6.5.4
  - tqdm=4.67.3
  - traitlets=5.14.3
  - treelite=4.6.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - uc-micro-py=1.0.3
  - ucx=1.19.1
  - ucxx=0.48.00
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.6.3
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.46.3
  - xarray=2025.6.1
  - xerces-c=3.2.5
  - xgboost=3.1.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
prefix: /home/Yamato/miniforge3/envs/aml-elliptic-gpu
